seecode/apps/node/urls.py
# coding: utf-8

from django.urls import path

from seecode.apps.node.views import host
from seecode.apps.node.views import service
from seecode.apps.node.views import upgrade


urlpatterns = [
    path(r'', host.index),
    path(r'service/', service.index),
    path(r'upgrade/', upgrade.index),
    path(r'upgrade/<int:upgrade_id>/', upgrade.show),
    path(r'upgrade/download/<int:upgrade_id>/', upgrade.download),

]

seecode/apps/scan/urls.py
# -*- coding: utf-8 -*-
from django.urls import path

from seecode.apps.scan.views import task
from seecode.apps.scan.views import issue
from seecode.apps.scan.views import group
from seecode.apps.scan.views import scan_template
from seecode.apps.scan.views import scan_template_item

urlpatterns = [

    # settings
    path(r'group/', group.index),
    path(r'group/<int:group_id>/', group.show),
    path(r'group/search/', group.search),
    path(r'group/batch/', group.batch),

    path(r'task/', task.index),
    path(r'task/<int:task_id>/', task.show),
    path(r'log/<int:task_id>/', task.download_log),
    path(r'task/batch/', task.batch),
    path(r'<int:task_id>/issue/', issue.index),
    path(r'issue/', issue.index),
    path(r'issue/<int:issue_id>/', issue.show),

    # scan template
    path(r'template/', scan_template.index),
    path(r'template/<int:profile_id>/', scan_template.show),
    path(r'template/tactic/', scan_template.tactic),
    
    # scan template items
    path(r'template/<int:template_id>/tactics/', scan_template_item.index),

]

seecode/apps/system/urls.py
from django.urls import path

from seecode.apps.system.views import settings
from seecode.apps.system.views import account
from seecode.apps.system.views import group
from seecode.apps.system.views import permission
from seecode.apps.system.views import syslog
from seecode.apps.system.views import service
from seecode.apps.system.views import sched
from seecode.apps.system.views import lang


urlpatterns = [

    # settings
    path(r'settings/', settings.index),
    path(r'clear/', settings.clear_cached),


    # account
    path(r'account/', account.index),
    path(r'account/token/', account.token),
    path(r'account/<int:user_id>/', account.show),
    path(r'account/search/', account.search),
    path(r'group/', group.index),
    path(r'group/<int:group_id>/', group.show),
    path(r'group/member/<int:group_id>/', group.member_index),
    path(r'account/perm/', permission.index),
    path(r'account/perm/<int:perm_id>/', permission.show),
    path(r'account/perm/batch/', permission.delete),

    # syslog
    path(r'log/', syslog.index),
    path(r'log/<int:syslog_id>', syslog.show),

    path(r'service/', service.index),
    path(r'service/<int:s_id>/', service.show),
    path(r'service/sched/', sched.index),

    # lang
    path(r'lang/', lang.index),

]

seecode/urls.py
from django.conf import settings
from django.urls import path
from django.conf.urls import url, include
from django.conf.urls.static import static

from cas import views

try:
    import debug_toolbar
except ImportError:
    pass

import seecode.apps.authenticate.views.auth as authview
import seecode.apps.system.views.home as home

urlpatterns = [
        path('', home.index),
]

if settings.ENABLE_CAS_SSO:
    urlpatterns += [
        path(r'login/', views.login, name='login'),
        path(r'logout/', views.logout, name='logout'),
    ]
else:
    urlpatterns += [
        path('login/', authview.login),
        path('logout/', authview.logout),
    ]

urlpatterns += [
    url(r'^api/v2/', include('seecode.apps.api.v2.urls'))
]

urlpatterns += [
    path('sys/', include('seecode.apps.system.urls'))
]

urlpatterns += [
    path('node/', include('seecode.apps.node.urls'))
]

urlpatterns += [
    path('project/', include('seecode.apps.project.urls'))
]

urlpatterns += [
    path('scan/', include('seecode.apps.scan.urls'))
]

urlpatterns += [
    path('tactic/', include('seecode.apps.tactic.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.UPLOAD_URL, document_root=settings.UPLOAD_ROOT)
    try:
        urlpatterns += [
            path('__debug__/', include(debug_toolbar.urls)),
        ]
    except:
        pass

seecode/apps/node/models.py
# coding: utf-8
from __future__ import unicode_literals

from django.db import models
from django.utils.encoding import python_2_unicode_compatible

from seecode.libs.core.enum import SERVICE_STATUS_TYPE, NODE_ROLE_TYPE
from seecode.libs.core.enum import CHANGELOG_MODULE_TYPE, CHANGELOG_ACTION_TYPE


@python_2_unicode_compatible
class HostInfo(models.Model):
    is_role_ui = models.BooleanField(default=False)
    is_role_client = models.BooleanField(default=False)
    hostname = models.CharField(max_length=32, null=True)
    ipv4 = models.CharField(max_length=64)
    ipv6 = models.CharField(max_length=64, null=True)
    ui_version = models.CharField(max_length=32, null=True)
    client_version = models.CharField(max_length=32, null=True)

    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.hostname

    class Meta:
        verbose_name = u"集群节点"
        verbose_name_plural = verbose_name
        db_table = u'sca_node_host'


@python_2_unicode_compatible
class ServiceInfo(models.Model):
    name = models.CharField(max_length=32, verbose_name='名称')
    key = models.CharField(max_length=128, verbose_name='关键字')
    role = models.SmallIntegerField(choices=NODE_ROLE_TYPE, verbose_name='角色')
    process_keyword = models.CharField(max_length=255, verbose_name='进程关键字')
    description = models.TextField(null=True)

    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = u"配置服务"
        verbose_name_plural = verbose_name
        db_table = u'sca_node_service'


@python_2_unicode_compatible
class HostServiceInfo(models.Model):
    host = models.ForeignKey(HostInfo, on_delete=models.CASCADE)
    service = models.ForeignKey(ServiceInfo, on_delete=models.CASCADE)
    ppid = models.IntegerField(verbose_name='父进程', null=True)
    pid = models.IntegerField(verbose_name='进程', null=True)
    status = models.SmallIntegerField(choices=SERVICE_STATUS_TYPE, verbose_name='状态')

    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = u"节点服务"
        verbose_name_plural = verbose_name
        db_table = u'sca_node_host_service'


@python_2_unicode_compatible
class UpgradePackageInfo(models.Model):
    name = models.CharField(max_length=32, verbose_name='名称')
    version = models.CharField(max_length=32, verbose_name='版本')
    changelog = models.TextField(null=True, verbose_name='历史')
    description = models.TextField(null=True, verbose_name='描述')
    hash = models.CharField(max_length=255, verbose_name='hash')
    path = models.CharField(max_length=255, null=True)
    is_archive = models.BooleanField(default=False)
    role = models.SmallIntegerField(choices=NODE_ROLE_TYPE, verbose_name='角色')
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = u"升级包"
        verbose_name_plural = verbose_name
        db_table = u'sca_upgrade_package'


@python_2_unicode_compatible
class UpgradeVersionInfo(models.Model):
    major = models.IntegerField(default=1)
    minor = models.IntegerField(default=0)
    revision = models.IntegerField(default=0)
    role = models.SmallIntegerField(choices=NODE_ROLE_TYPE, verbose_name='角色')
    
    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = u"升级版本"
        verbose_name_plural = verbose_name
        db_table = u'sca_upgrade_version'


@python_2_unicode_compatible
class UpgradeChangelogInfo(models.Model):
    is_archive = models.BooleanField(default=False)
    action = models.SmallIntegerField(choices=CHANGELOG_ACTION_TYPE)
    module = models.SmallIntegerField(choices=CHANGELOG_MODULE_TYPE, verbose_name='模块')
    version = models.CharField(max_length=16, null=True)
    description = models.TextField()

    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = u"升级版本"
        verbose_name_plural = verbose_name
        db_table = u'sca_upgrade_changelog'

seecode/apps/system/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.contrib.contenttypes.models import ContentType
from django_celery_beat.models import CrontabSchedule
from django_celery_beat.models import IntervalSchedule
from django.contrib.auth.models import User

from seecode.libs.core.enum import SYSLOG_LEVEL
from seecode.libs.core.enum import SYSLOG_TYPE
from seecode.libs.core.enum import SCHED_TYPE
from seecode.libs.core.enum import WIDGET_TYPE
from seecode.libs.core.enum import EMPLOYEE_STATUS
from seecode.libs.core.enum import GENDER_TYPE


@python_2_unicode_compatible
class TagInfo(models.Model):
    name = models.CharField(max_length=128, verbose_name='名称')
    description = models.TextField(null=True, verbose_name='描述')
    parent = models.ForeignKey('self', null=True, verbose_name='父亲分类', on_delete=models.DO_NOTHING)

    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = u"Tag"
        verbose_name_plural = verbose_name
        db_table = u'sca_common_tag'


@python_2_unicode_compatible
class SyslogInfo(models.Model):
    title = models.CharField(max_length=128, verbose_name='标题')
    description = models.TextField(null=True, verbose_name='消息内容')
    stack_trace = models.TextField(null=True, verbose_name='堆栈信息')
    module = models.ForeignKey(ContentType, null=True, verbose_name='问题模块', on_delete=models.CASCADE)
    object_id = models.IntegerField(null=True)
    ipv4 = models.CharField(max_length=20, null=True, verbose_name='ipv4')
    type = models.SmallIntegerField(choices=SYSLOG_TYPE, default=1)
    level = models.SmallIntegerField(choices=SYSLOG_LEVEL, default=4, verbose_name='日志级别')
    is_read = models.BooleanField(default=False)

    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = u"Syslog"
        verbose_name_plural = verbose_name
        db_table = u'sca_common_syslog'


@python_2_unicode_compatible
class SchedInfo(models.Model):
    name = models.CharField(max_length=128, verbose_name='标题')
    type = models.SmallIntegerField(choices=SCHED_TYPE, default=1)
    crontab = models.ForeignKey(CrontabSchedule, null=True, on_delete=models.CASCADE)
    interval = models.ForeignKey(IntervalSchedule, null=True, on_delete=models.CASCADE)

    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = u"Syslog"
        verbose_name_plural = verbose_name
        db_table = u'sca_common_sched'


@python_2_unicode_compatible
class ConfigInfo(models.Model):
    site = models.CharField(max_length=256, verbose_name='站点名称')
    content = models.TextField(null=True, verbose_name='系统配置')

    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.site

    class Meta:
        verbose_name = u"系统配置表"
        verbose_name_plural = verbose_name
        db_table = u'sca_common_config'


@python_2_unicode_compatible
class LanguageInfo(models.Model):
    name = models.CharField(max_length=16, verbose_name='名称')
    suffix = models.CharField(max_length=255, verbose_name='后缀', null=True)
    key = models.TextField(null=True, verbose_name='key')
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = u"开发语言"
        verbose_name_plural = verbose_name
        db_table = u'sca_conf_language'

seecode/apps/node/views/host.py
# coding: utf-8
from __future__ import unicode_literals

from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.views.decorators.csrf import ensure_csrf_cookie

from seecode.apps.node.models import HostInfo
from seecode.libs.core.enum import NODE_ROLE_TYPE
from seecode.libs.paginator import Paginator
from seecode.libs.units import parse_int


@login_required
@ensure_csrf_cookie
def index(request):
    """
    :param request:
    :return:
    """
    cate = request.GET.get('c', '')
    keyword = request.GET.get('k', '')

    page_num = parse_int(request.GET.get('p', 1), 1)
    page_size = parse_int(request.GET.get('ps', 20), 20)

    sql_where = {}

    if cate:
        sql_where['origin__id'] = int(cate)

    items = HostInfo.objects.filter(**sql_where).order_by('-created_at')
    paginator = Paginator(items, page_size, request=request, pre_name=u"节点")
    page = paginator.page(page_num)

    return render(request, 'node/host/index.html', {
        'nav': 'node',
        'page': page,
        'keyword': keyword,
        'node_role': NODE_ROLE_TYPE,
    })


@login_required
@ensure_csrf_cookie
def show(request, node_id):
    """
    :param request:
    :param node_id:
    :return:
    """
    try:
        model = HostInfo.objects.get(id=node_id)

    except HostInfo.DoesNotExist as ex:
        model = None

    return render(request, 'node/host/edit.html', {
        'nav': 'node',
        'model': model,
    })

seecode/apps/node/views/service.py
# coding: utf-8
from __future__ import unicode_literals

import codecs
import json
import uuid

from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.utils.http import urlquote
from django.views.decorators.csrf import ensure_csrf_cookie

from seecode.apps.node.models import ServiceInfo
from seecode.libs.core.enum import NODE_ROLE_TYPE
from seecode.libs.dal.engine import get_all_engine
from seecode.libs.dal.service import create_service_obj
from seecode.libs.paginator import Paginator
from seecode.libs.units import parse_int


@login_required
@ensure_csrf_cookie
def index(request):
    """
    :param request:
    :return:
    """
    if request.method == "POST":
        try:
            save(request)
            name = request.POST.get('name', '')
            msg = urlquote(' "{0}" 服务注册成功!'.format(name))
            return HttpResponseRedirect('/node/service/?msg={0}'.format(msg))
        except Exception as ex:
            import traceback;
            traceback.print_exc()
            return HttpResponseRedirect('/node/service/?errmsg={0}'.format(urlquote(str(ex))))
    else:
        action = request.GET.get('action', '')
        if action:
            items = ServiceInfo.objects.all()
            services = []
            for item in items:
                services.append({
                    'name': item.name,
                    'key': item.key,
                    'role': 'ui' if item.role == 1 else 'client',
                    'keyword': item.process_keyword
                })
            response = HttpResponse(json.dumps(services, indent=2), content_type='application/json')
            response['Content-Disposition'] = 'attachment; filename="services.json"'
            response.write(codecs.BOM_UTF8)
            return response

        else:
            keyword = request.GET.get('k', '')
            page_num = parse_int(request.GET.get('p', 1), 1)
            page_size = parse_int(request.GET.get('ps', 20), 20)
            sql_where = {}
            if keyword:
                sql_where['name__icontains'] = keyword.strip()

            items = ServiceInfo.objects.filter(**sql_where).order_by('-created_at')
            paginator = Paginator(items, page_size, request=request, pre_name=u"服务")
            page = paginator.page(page_num)

            return render(request, 'node/service/index.html', {
                'nav': 'node',
                'page': page,
                'keyword': keyword,
                'engines': get_all_engine(),
                'node_role': NODE_ROLE_TYPE,
            })


@login_required
def save(request):
    """
    :param request:
    :return:
    """
    result = None
    name = request.POST.get('name', '')
    process_keyword = request.POST.get('process_keyword', '')
    role = request.POST.get('role', '')
    description = request.POST.get('description', '')

    if not all((name, process_keyword)):
        raise Exception('"name, process_keyword" 参数不能为空!')

    service_obj = create_service_obj(
        name=name,
        process_keyword=process_keyword,
        role=role,
        description=description,
        key=uuid.uuid4().hex
    )

seecode/templates/scan/task/show.html
{% extends "base.html" %}
{% block body %}
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <h1>任务管理
      <small>{{model.app.module_name}}</small>
    </h1>
    <ol class="breadcrumb">
      <li><a href="/"><i class="fa fa-dashboard"></i> Home</a></li>
      <li>任务管理</li>
      <li><a href="/scan/task/">扫描任务</a></li>
      <li><a href="/project/app/{{model.app.id}}/">{{model.app.app_name}}</a></li>
      <li class="active">{{model.start_time|date:"Y-m-d H:i:s"|default:"-" }}</li>
    </ol>
  </section>
  <!-- Main content -->
  <section class="content">
    <div class="row">
      <div class="col-xs-12">
        <!-- /.box-header -->
        <form enctype="multipart/form-data" method="post">
          {% csrf_token %}{% if model%}
          <input name="intel_id" type="hidden" value="{{ model.id }}"/>{%endif%}
          <div class="nav-tabs-custom">
            <ul class="nav nav-tabs">
              <li class="active"><a data-toggle="tab" href="#fa-icons">基本信息</a></li>
              <li><a href="#conf" data-toggle="tab">扫描配置</a></li>
              <li><a href="#history" data-toggle="tab">扫描历史</a></li>
            </ul>
            <div class="tab-content">
              <!-- base -->
              <div class="tab-pane active" id="fa-icons">
                <div class="table-responsive">
                  <table class="table">
                    <tr>
                      <th style="border: 0px;width:130px; padding-left: 35px;">应用名称：</th>
                      <td align="left" style="border: 0px;"><a href="/project/app/{{model.app.id}}/">{{model.app.app_name}}</a>
                      </td>
                    </tr>
                    <tr>
                      <th style="padding-left: 35px;">应用模块：</th>
                      <td align="left"><span class="label label-default">{{model.app.module_name}}</span></td>
                    </tr>
                    <tr>
                      <th style="padding-left: 35px;">开始时间：</th>
                      <td align="left">{{model.start_time|date:"Y-m-d H:i:s"|default:"-"}}</td>
                    </tr>
                    <tr>
                      <th style="padding-left: 35px;">结束时间：</th>
                      <td align="left">{{model.end_time|date:"Y-m-d H:i:s"|default:"-"}}</td>
                    </tr>
                    <tr>
                      <th style="padding-left: 35px;">触发方式：</th>
                      <td align="left">{%if model.scan_way == 1%}
                        <span class="label bg-fuchsia-active">{{model.get_scan_way_display}}</span>
                        {%else%}<span class="label bg-teal-active">{{model.get_scan_way_display}}</span>{%endif%}
                      </td>
                    </tr>
                    <tr>
                      <th style="padding-left: 35px;">扫描节点：</th>
                      <td align="left">{{model.executor_ip|default:"-"}}</td>
                    </tr>
                    <tr>
                      <th style="padding-left: 35px;">扫描 Hash：</th>
                      <td align="left">{{model.hash|slice:8|default:"-"}}</td>
                    </tr>
                    <tr>
                      <th style="padding-left: 35px;">风险信息：</th>
                      <td align="left">
                        <span class="badge" style="background: #F96C60">
                  {% if model.critical%}
                  <a href="/scan/issue/?r=1&app={{model.app.id}}&c=3" style="color:#fff"
                     title="严重: {{ model.critical}}">{{ model.critical}}</a>{%else%}{{ model.critical}}{%endif%}</span>
                        <span class="badge" style="background: #FBB321">
                     {% if model.high%}<a href="/scan/issue/?r=2&app={{model.app.id}}&c=3" style="color:#fff" title="高危: {{ model.high}}">{{ model.high}}</a>{%else%}{{ model.high}}{%endif%}
                  </span> <span class="badge" style="background: #41CAC0">{% if model.medium%}
                  <a href="/scan/issue/?r=3&app={{model.app.id}}&c=3" style="color:#fff" title="中危:{{ model.medium}}">{{ model.medium}}</a>{%else%}{{ model.medium}}{%endif%}
                  </span> <span class="badge " style="background: #3C8DBC">{% if model.low%}
                  <a href="/scan/issue/?r=4&app={{model.app.id}}&c=3" style="color:#fff" title="低危:{{ model.low}}">{{ model.low}}</a>{%else%}{{ model.low}}{%endif%}</span></td>
                    </tr>
                    <tr>
                      <th style="padding-left: 35px;">任务状态：</th>
                      <td align="left">{% if model.status == １%}
                        <span class="label label-danger tooltip_func" title="{{model.error_title|default:""}}">
                        {{model.get_status_display}} </span>
                        <a href="/sys/log/?k={{model.error_title}}"><i class="fa fa-fw fa-exclamation-circle" style="color:#000"></i></a>
                        {%elif model.status == 2%} <span class="label label-warning tooltip_func" title="{{model.error_title|default:""}}">{{model.get_status_display}}</span>
                        {%elif model.status|slugify in '3,4,5'%} <span - class="label label-info tooltip_func" title="{{model.error_title|default:""}}">{{model.get_status_display}}</span>
                        {%else%} <span - class="label label-success tooltip_func" title="{{model.error_title|default:""}}">{{model.get_status_display}}</span>{%endif%}
                      </td>
                    </tr>
                    {% if model.status == １%}
                    <tr>
                      <th style="padding-left: 35px;">错误堆栈：</th>
                      <td align="left"><pre>{{model.error_reason}}</pre></td>
                    </tr>
                    {%endif%}
                    <tr>
                      <th style="padding-left: 35px;">代码同步：</th>
                      <td align="left">{%if model.is_force_scan%}强制同步{%else%}不同步{%endif%}</td>
                    </tr>
                    <tr>
                      <th style="padding-left: 35px;">相关信息：</th>
                      <td align="left"><a href="/scan/issue/?app={{model.app.id}}"><span class="label label-default">查看扫描结果</span></a></td>
                    </tr>
                    <tr>
                      <td></td>
                      <td><button class="btn btn-warning" onclick="javascript:window.history.back()" type="button">返回</button></td>
                    </tr>
                  </table>
                </div>
              </div>
              <!-- /#fa-icons -->
              <div class="tab-pane" id="conf">
                <div class="table-responsive">
                  <table class="table">
                    <tr>
                      <th style="border: 0px;width:130px; padding-left: 35px;">扫描模板：</th>
                      <td align="left">
                        <a href="/scan/template/?k={{model.template_name}}">{{model.template_name}} - v{{model.template_version|default:"0.0"}}</a>
                      </td>
                    </tr>
                    <tr>
                      <th style="padding-left: 35px;">扫描日志：</th>
                      <td align="left">{%if model.log_file%}<a href="/scan/log/{{model.id}}/">{{model.log_file|default:"-"}}</a>{%else%}-{%endif%}</td>
                    </tr>
                    <tr>
                      <th style="padding-left: 35px;">任务配置：</th>
                      <td align="left"><pre>{{% for key, value in config.items %}
  "{{key}}": "{{value}}"{% endfor %}
}</pre>
                      </td>
                    </tr>
                    <tr>
                      <td></td>
                      <td><button class="btn btn-warning" onclick="javascript:window.history.back()" type="button">返回</button></td>
                    </tr>
                  </table>
                </div>
              </div>

              <div class="tab-pane" id="history">
                <div class="table-responsive">
                  <table class="table table-striped table-borderless">
                    <thead>
                    <tr>
                      <th>编号</th>
                      <th>时间</th>
                      <th>LEVEL</th>
                      <th>状态</th>
                      <th>阶段</th>
                      <th>说明</th>
                    </tr>
                    </thead>
                    <tbody>
                    {%for item in history%}
                    <tr>
                      <td>{{forloop.counter}}</td>
                      <td><span class="label bg-purple-active">{{item.created_at|date:"Y-m-d H:i:s"|default:"-"}}</span></td>
                      <td>{%if item.level == 4%}<span class="label bg-teal-active">{{item.get_level_display}}</span>
                        {%elif item.level == 2%}<span class="label label-danger">{{item.get_level_display}}</span>
                        {%elif item.level == 3%}<span class="label label-warning">{{item.get_level_display}}</span>
                        {%else%}<span class="label label-primary">{{item.get_level_display}}</span>{%endif%}
                      </td>
                      <td>{% if item.status == １%}<span class="label label-danger ">{{item.get_status_display}}</span>
                        {%elif item.status == 2%}<span class="label label-warning">{{item.get_status_display}}</span>
                        {%elif item.status|slugify in '3,4'%}<span class="label label-primary">{{item.get_status_display}}</span>
                        {%elif item.status == 5%}<span class="label label-info">{{item.get_status_display}}</span>
                        {%else%}<span class="label label-success">{{item.get_status_display}}</span>{%endif%}
                      </td>
                      <td>{{item.title}}</td>
                      <td>{{item.description|default:"-"}}</td>
                    </tr>
                    {% empty %}
                    <tr><td colspan="10" align="center"><span style="color:#ff0000">没找到相关数据!</span></td></tr>
                    {%endfor%}
                    <tr><td colspan="10"><strong>扫描耗时： </strong>{{time_consumed|default:"-"}}</td></tr>
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
            <!-- /.tab-content -->
          </div>
          <!-- /.nav-tabs-custom -->

        </form>
        <!-- /.col -->
      </div>
    </div>
    <!-- /.row -->
  </section>
  <!-- /.content -->
</div>
{% endblock %}

{% block script %}

{% endblock %}